[project]
name = ""
version = "0.0.1"
dependencies = [
    "fastapi",
    "uvicorn",
    "litellm",
    "python-dotenv",
    "httpx",
    "rich",
    "pandas",
    "weave>=0.51.48",
]

[tool.uv]
package = false
